### ISSUE TITLE
ImportError: No module named 'batch_norm'   python2????

### ISSUE THREAD

**Issue by c1a1o1** [jerryli27/TwinGAN#6]
E:\Users\Raytine\Anaconda3\python.exe F:/zhaiyao/TwinGAN-master/pggan_runner.py
Traceback (most recent call last):
  File "F:/zhaiyao/TwinGAN-master/pggan_runner.py", line 39, in <module>
    import image_generation
  File "F:\zhaiyao\TwinGAN-master\image_generation.py", line 35, in <module>
    from libs import ops
  File "F:\zhaiyao\TwinGAN-master\libs\ops.py", line 22, in <module>
    import libs.instance_norm
  File "F:\zhaiyao\TwinGAN-master\libs\instance_norm.py", line 21, in <module>
    from batch_norm import get_conditional_batch_norm_param
ImportError: No module named 'batch_norm'

Process finished with exit code 1

**Comment by jerryli27** [comment]
This issue seems similar to https://github.com/jerryli27/TwinGAN/issues/7. Both has to do with unable to import modules. I am closing this issue to consolidate two into one.
