### ISSUE TITLE
ImportError: No module named 'pggan_utils'

### ISSUE THREAD

**Issue by c1a1o1** [jerryli27/TwinGAN#7]
E:\Users\Raytine\Anaconda3\python.exe F:/zhaiyao/TwinGAN-master/pggan_runner.py
Traceback (most recent call last):
  File "F:/zhaiyao/TwinGAN-master/pggan_runner.py", line 39, in <module>
    import image_generation
  File "F:\zhaiyao\TwinGAN-master\image_generation.py", line 40, in <module>
    from nets import pggan
  File "F:\zhaiyao\TwinGAN-master\nets\pggan.py", line 19, in <module>
    from pggan_utils import pggan_utils
ImportError: No module named 'pggan_utils'

**Comment by jerryli27** [comment]
Your code does not seem to be the same as the master branch. I guess this issue is similar to https://github.com/jerryli27/TwinGAN/issues/3 , especially the "PYTHONPATH" part.

**Comment by jerryli27** [comment]
Closing due to lack of activity. Please reopen if the issue persists.
